### ISSUE TITLE
Hello，I want to use LLVM on Windows,but I can't find_package(LLVM REQUIRED CONFIG)

### ISSUE THREAD

**Issue by harrisonGPU** [ioncodes/docker-compiler-explorer#1]
Let me tell you some retails：
First，I git clone llvm-project. The path is `D:\llvm-project`
And then :
`cd llvm-project`
`mkdir build`
`cd build`
`cmake -G "Visual Studio 16 2019" ../llvm`
`cmake --build . --target install`
Do above these commands,I build my project.The path is `D:\kaleodoscope`,and then:
`cd kaleodoscope`
`mkdir build`
`cd build`
`cmake ..`
it will be error!
this is  
[CMakeOutput.log](https://github.com/tsnl/pdm/files/9784182/CMakeOutput.log)
```
Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30146.0
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
Thanks a lot !

**Comment by harrisonGPU** [comment]
My project is [this](https://github.com/ejunjsh/kaleidoscope)

**Comment by ioncodes** [comment]
I fail to understand why you opened an issue for this on this repo. If you just want to ask a question, hit me up on [Twitter](https://twitter.com/layle_ctf) or Discord `Layle#6969`. Regardless, I have only little experience with LLVM on Windows but the process I described [here](https://layle.me/using-llvm-with-cmake/) worked for me on Windows.

**Comment by harrisonGPU** [comment]
> I fail to understand why you opened an issue for this on this repo. If you just want to ask a question, hit me up on [Twitter](https://twitter.com/layle_ctf) or Discord `Layle#6969`. Regardless, I have only little experience with LLVM on Windows but the process I described [here](https://layle.me/using-llvm-with-cmake/) worked for me on Window。

Thanks a lot！
